// ywai/internal/control/web/src/components/shared/YdSelect.tsx
import { useState, useRef, useEffect, useCallback, useMemo } from "react";
import { ChevronDown } from "lucide-react";
import { useAnchored } from "../../hooks/useAnchored";

export interface SelectOption {
  value: string;
  label: string;
}

interface YdSelectProps {
  options: SelectOption[];
  value: string;
  onChange: (value: string) => void;
  placeholder?: string;
  disabled?: boolean;
  className?: string;
}

/**
 * Themed select dropdown (replaces native <select>, which can't be styled
 * to match the dark-glass theme). Uses yz-ui CSS classes from components.css.
 *
 * Port of Angular `yd-select.component.ts`.
 */
export default function YdSelect({
  options,
  value,
  onChange,
  placeholder = "Seleccionar",
  disabled = false,
  className,
}: YdSelectProps) {
  const [open, setOpen] = useState(false);
  const menuRef = useRef<HTMLDivElement>(null);
  const hostRef = useRef<HTMLDivElement>(null);

  const selectedLabel = useMemo(
    () => options.find((o) => o.value === value)?.label ?? placeholder,
    [options, value, placeholder],
  );

  const hasSelection = useMemo(
    () => options.some((o) => o.value === value),
    [options, value],
  );

  const toggle = useCallback(
    (e: React.MouseEvent) => {
      e.stopPropagation();
      if (!disabled) setOpen((v) => !v);
    },
    [disabled],
  );

  const pick = useCallback(
    (v: string) => {
      onChange(v);
      setOpen(false);
    },
    [onChange],
  );

  // Close on document click outside host.
  useEffect(() => {
    if (!open) return;
    const handler = (e: MouseEvent) => {
      if (hostRef.current && !hostRef.current.contains(e.target as Node)) {
        setOpen(false);
      }
    };
    document.addEventListener("mousedown", handler);
    return () => document.removeEventListener("mousedown", handler);
  }, [open]);

  // Position the popover (flip + clamp).
  useAnchored(menuRef, open);

  return (
    <div
      ref={hostRef}
      className={`yd-select${open ? " open" : ""}${className ? ` ${className}` : ""}`}
    >
      <button
        type="button"
        className="yd-select-trigger"
        disabled={disabled}
        onClick={toggle}
      >
        <span className={`yd-select-label${!hasSelection ? " is-ph" : ""}`}>
          {selectedLabel}
        </span>
        <ChevronDown size={16} strokeWidth={2.5} />
      </button>
      {open && (
        <div ref={menuRef} className="yd-pop yd-select-menu yd-menu-docked">
          {options.map((o) => (
            <button
              key={o.value}
              type="button"
              className={`yd-select-opt${o.value === value ? " sel" : ""}`}
              onClick={() => pick(o.value)}
            >
              {o.label}
            </button>
          ))}
        </div>
      )}
    </div>
  );
}

// ywai/skills/yz-ui/assets/angular/yd-select.component.ts
import { Component, ChangeDetectionStrategy, signal, computed, input, output, HostListener, ElementRef, inject } from '@angular/core';
import { LucideAngularModule } from 'lucide-angular';

export interface SelectOption { value: string; label: string; }

/**
 * Themed select dropdown (replaces native <select>, which can't be styled
 * to match the dark-glass theme). Signals + native control flow.
 *
 * Usage: <yd-select [options]="opts" [value]="env()" (valueChange)="env.set($event)" />
 */
@Component({
  selector: 'yd-select',
  standalone: true,
  imports: [LucideAngularModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="yd-select" [class.open]="open()">
      <button type="button" class="yd-select-trigger" (click)="toggle($event)">
        <span class="yd-select-label">{{ selectedLabel() }}</span>
        <lucide-icon name="chevron-down" [size]="15" />
      </button>
      @if (open()) {
        <div class="yd-pop yd-select-menu yd-menu-docked">
          @for (o of options(); track o.value) {
            <button type="button" class="yd-select-opt" [class.sel]="o.value === value()" (click)="pick(o.value)">{{ o.label }}</button>
          }
        </div>
      }
    </div>
  `,
})
export class YdSelectComponent {
  private readonly host = inject(ElementRef);
  readonly options = input<SelectOption[]>([]);
  readonly value = input<string>('');
  readonly placeholder = input<string>('Seleccionar');
  readonly valueChange = output<string>();

  readonly open = signal(false);
  readonly selectedLabel = computed(() =>
    this.options().find((o) => o.value === this.value())?.label ?? this.placeholder(),
  );

  toggle(e: Event): void { e.stopPropagation(); this.open.update((v) => !v); }
  pick(v: string): void { this.valueChange.emit(v); this.open.set(false); }

  @HostListener('document:click', ['$event'])
  onDocClick(e: Event): void {
    if (!this.host.nativeElement.contains(e.target)) this.open.set(false);
  }
}
